### ISSUE TITLE
Schema automator for OMOP: concept_class_id falsely inferred as idenitifier

### ISSUE THREAD

**Issue by matentzn** [linkml/schema-automator#109]
See #98 

When trying to infer the schema for all OMOP tables, concept_class_id is inferred to be an identifier, while this should be a foreign key (or nothing).

```
concept_class_id:
    examples:
    - value: RNA Variant
    from_schema: https://w3id.org/omop_vocabulary
    identifier: true
    range: string
```
