### ISSUE TITLE
Support rdfs:domain and rdfs:range in generated schema by `import-rdfs`

### ISSUE THREAD

**Issue by jo-fra** [linkml/schema-automator#154]
When generating a LinkML schema using `schemauto import-rdfs` the resulting LinkML schema does not incorporate the rdfs:domain and rdfs:range definitions.

E.g. the following excerpt from [FOAF](http://xmlns.com/foaf/spec/):
```ttl
###  http://xmlns.com/foaf/0.1/knows
foaf:knows rdf:type owl:ObjectProperty ;
           rdfs:domain foaf:Person ;
           rdfs:range foaf:Person ;
           rdfs:comment "A person known by this person (indicating some level of reciprocated interaction between the parties)." ;
           rdfs:isDefinedBy <http://xmlns.com/foaf/0.1/> ;
           rdfs:label "knows" .

###  http://xmlns.com/foaf/0.1/Person
foaf:Person rdf:type owl:Class ;
            rdfs:subClassOf <http://www.w3.org/2003/01/geo/wgs84_pos#SpatialThing> ,
                            foaf:Agent ;
            owl:disjointWith foaf:Project ;
            rdfs:comment "A person." ;
            rdfs:isDefinedBy <http://xmlns.com/foaf/0.1/> ;
            rdfs:label "Person" .
```

results in the the following LinkML schema:
```yaml
slots:
  knows:
    comments:
    - A person known by this person (indicating some level of reciprocated interaction
      between the parties).
    slot_uri: foaf:knows

classes:
  Person:
    comments:
    - A person.
    is_a: Agent
    class_uri: foaf:Person
```

I would expect that rdfs:domain and rdfs:range of foaf:knows property is incorporated like:
```
slots:
  knows:
    comments:
    - A person known by this person (indicating some level of reciprocated interaction
      between the parties).
    slot_uri: foaf:knows
    range: Person

classes:
  Person:
    comments:
    - A person.
    is_a: Agent
    class_uri: foaf:Person
    slots: 
    - knows
```

**Comment by multimeric** [comment]
I believe I've fixed this in #152. Can you please test that branch to let me know if it resolves your issue?

**Comment by jo-fra** [comment]
@multimeric 
I tested it with the latest commit (cfe7e15563ee1cf681b3eb266eb9ab8754f0c39c) of https://github.com/linkml/schema-automator/pull/152 and with that I do not get the expected results. However, looking at the diff it shows that you reverted some changes in `schema_automator/importers/rdfs_import_engine.py` when merging from https://github.com/linkml/schema-automator/pull/151, e.g.: 

https://github.com/linkml/schema-automator/pull/152/commits/cfe7e15563ee1cf681b3eb266eb9ab8754f0c39c#diff-b6464c40227100611b000caf1086c351935db40bcf0f78ca606ca68d94e5ca3fL37-L43:
```
<<<<<<< HEAD
    "domain_of": [HTTP_SDO.domainIncludes, SDO.domainIncludes, RDFS.domain],
    "range": [HTTP_SDO.rangeIncludes, SDO.rangeIncludes, RDFS.range],
=======
    "domain_of": [HTTP_SDO.domainIncludes, SDO.domainIncludes],
    "rangeIncludes": [HTTP_SDO.rangeIncludes, SDO.rangeIncludes],
>>>>>>> cleanup-deps
```

After testing it with commit 65869ba4d7739302e352ac02a8354a5746e89f34 before the merge `rdfs:domain` and `rdfs:range` are incorporated expected!

Was the revert of that changes unintended?


Just two caveats:
1. the generated schema has `default_prefix: example` but it is not defined in `prefixes`:
    ```yaml
    prefixes:
      linkml: https://w3id.org/linkml/
      dc: http://purl.org/dc/elements/1.1/
      vs: http://www.w3.org/2003/06/sw-vocab-status/ns#
      owl: http://www.w3.org/2002/07/owl#
      wot: http://xmlns.com/wot/0.1/
      foaf: http://xmlns.com/foaf/0.1/
      rdfs: http://www.w3.org/2000/01/rdf-schema#
    default_prefix: example
    ```

2. All datatype properties with `rdfs:range rdfs:Literal` are generated with `range: Literal` e.g. 
    ```yaml
    slots:
      jabberID:
        comments:
        - A jabber ID for something.
        slot_uri: foaf:jabberID
        range: Literal
    ```
    However `Literal` is unrecognized and I am getting this error when trying to run `gen-python` with this schema:
    ```shell
    gen-python foaf_schema.yaml
    ValueError: File "foaf_schema.yaml", line 21, col 12 slot: jabberID - unrecognized range (Literal)
    ```

**Comment by multimeric** [comment]
Thanks for the report. It probably was just a faulty merge. I'll likely fix it early next week.

**Comment by multimeric** [comment]
Okay, I've rebased and hopefully fixed the underlying issue.

**Comment by jo-fra** [comment]
@multimeric  Thanks, I tried it with the latest commit and it includes now `rdfs:domain` and `rdfs:range`.

Only this two issues still persist:

> 1. the generated schema has default_prefix: example but it is not defined in prefixes:
>     ```
>     prefixes:
>       linkml: https://w3id.org/linkml/
>       dc: http://purl.org/dc/elements/1.1/
>       vs: http://www.w3.org/2003/06/sw-vocab-status/ns#
>       owl: http://www.w3.org/2002/07/owl#
>       wot: http://xmlns.com/wot/0.1/
>       foaf: http://xmlns.com/foaf/0.1/
>       rdfs: http://www.w3.org/2000/01/rdf-schema#
>     default_prefix: example
>     ```
> 
> 2. All datatype properties with `rdfs:range rdfs:Literal` are generated with `range: Literal` e.g.
>     ```
>     slots:
>       jabberID:
>         comments:
>         - A jabber ID for something.
>         slot_uri: foaf:jabberID
>         range: Literal
>     ```
>     
>     However Literal is unrecognized and I am getting this error when trying to run gen-python with this schema:
>     ```
>     gen-python foaf_schema.yaml
>     ValueError: File "foaf_schema.yaml", line 21, col 12 slot: jabberID - unrecognized range (Literal)
>     ```

**Comment by multimeric** [comment]
Hmm, I can't replicate this `Literal` issue. If I `schemauto import-rdfs` on the following ttl:

```ttl
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

foaf:knows rdf:type owl:ObjectProperty ;
           rdfs:domain foaf:Person ;
           rdfs:range foaf:Person ;
           rdfs:comment "A person known by this person (indicating some level of reciprocated interaction between the parties)." ;
           rdfs:isDefinedBy <http://xmlns.com/foaf/0.1/> ;
           rdfs:label "knows" .

foaf:Person rdf:type owl:Class ;
            rdfs:subClassOf <http://www.w3.org/2003/01/geo/wgs84_pos#SpatialThing> ,
                            foaf:Agent ;
            owl:disjointWith foaf:Project ;
            rdfs:comment "A person." ;
            rdfs:isDefinedBy <http://xmlns.com/foaf/0.1/> ;
            rdfs:label "Person" .
```

I get:
```yaml
name: example
id: http://example.org/example
imports:
- linkml:types
prefixes:
  linkml: https://w3id.org/linkml/
  foaf: http://xmlns.com/foaf/0.1/
default_prefix: example
default_range: string
slots:
  knows:
    comments:
    - A person known by this person (indicating some level of reciprocated interaction
      between the parties).
    slot_uri: foaf:knows
    range: Person
classes:
  Agent:
    class_uri: foaf:Agent
  SpatialThing:
    class_uri: ns1:SpatialThing
  Person:
    comments:
    - A person.
    is_a: Agent
    slots:
    - knows
    class_uri: foaf:Person
```
