### ISSUE TITLE
OWL class restrictions are not generated in the expected way

### ISSUE THREAD

**Issue by hentoilusose** [linkml/schema-automator#159]
**Describe the bug**
When specifying class restrictions in OWL, they are not rendered into the expected LinkML structure. For example Object property between classes with a cardinality of [1..1] (from the MWE below) is rendered into:

```
slots:
  OProperty:
    slot_uri: https://foobar#OProperty
    multivalued: true
classes:
  A:
    slot_usage:
      OProperty:
        required: true
        multivalued: false
    class_uri: https://foobar#A
  B:
    class_uri: https://foobar#B
```
(the prefixes etc. are omitted)

Rendered into PlantUML from LinkML: 
![Image](https://github.com/user-attachments/assets/de16647f-1647-400d-8099-53595baba522)

**To Reproduce**
Render MWE into LinkML:
```
Ontology(<https://foobar>
Declaration(Class(<https://foobar#A>))
Declaration(Class(<https://foobar#B>))
Declaration(ObjectProperty(<https://foobar#OProperty>))
SubClassOf(<https://foobar#A> ObjectExactCardinality(1 <https://foobar#OProperty> <https://foobar#B>))
)
```

Used command: `schemauto import-owl test.ofn -o test.yaml`
Schema-automator version: 0.5.3

**Expected behavior**
```
slots:
  OProperty:
    slot_uri: https://foobar#OProperty
classes:
  B:
    class_uri: https://foobar#B
  A:
    slot_usage:
      OProperty:
        required: true
        multivalued: false
        exact_cardinality: 1
        range: B
    class_uri: https://foobar#A
```
(the prefixes etc. are omitted)

Rendered into PlantUML from LinkML:
![Image](https://github.com/user-attachments/assets/be4ae38f-5a4f-4b91-bbfb-b1316f57a9a1)
